// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Validar se as variáveis de ambiente estão definidas
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error('🔴 ERRO CRÍTICO: Variáveis de ambiente do Supabase não configuradas!');
  console.error('VITE_SUPABASE_URL:', SUPABASE_URL ? '✅ Definida' : '❌ Não definida');
  console.error('VITE_SUPABASE_PUBLISHABLE_KEY:', SUPABASE_PUBLISHABLE_KEY ? '✅ Definida' : '❌ Não definida');
  console.error('');
  console.error('📝 Para corrigir:');
  console.error('1. Crie um arquivo .env na raiz do projeto');
  console.error('2. Adicione as seguintes variáveis:');
  console.error('   VITE_SUPABASE_URL=https://seu-projeto.supabase.co');
  console.error('   VITE_SUPABASE_PUBLISHABLE_KEY=sua-chave-publica');
  console.error('3. Reinicie o servidor de desenvolvimento');
  console.error('');
  console.error('💡 As credenciais estão no arquivo CREDENCIAIS_DEPLOY.md');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL || 'https://placeholder.supabase.co', 
  SUPABASE_PUBLISHABLE_KEY || 'placeholder-key',
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);